### ISSUE TITLE
Getting users names 

### ISSUE THREAD

**Issue by sdmg15** [codeafrica/github-africa#6]
Hi, 
I wonder how i can get all users name of specify country

**Comment by AlekYaw** [comment]
Add a poll.. No one would release information like that.

**Comment by sdmg15** [comment]
How is it possible ? With github or un another website/?

**Comment by AlekYaw** [comment]
Not even sure if you would want to do that... It would have to be an user input which, by the very definition of user input- not very reliable. I would personally look on the countries list of said website that you are trying to acquire users from.   My ICQ is 677745213 if you have any more questions.

Have a good one

**Comment by sdmg15** [comment]
please be clear on you post i don't really understand what your are saying.
My own ICQ is 693149896. if you have a whatsapp account or more we can going there for futher our 
discussion!
